fix(*): Add dns_servers as configuration option
clouddrove/terraform-aws-client-vpn pull request #37
Opened 2024-05-29 09:54 UTC by Moep90

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting jira issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a Jira issue `#123`

2024-08-06 17:31 UTC, rhhammond commented on versions.tf
> +  required_version = ">= 1.5.7"
Maybe this is related to the Hashicorp BSL announcement last year?

[see item 7 on the FAQ](https://www.hashicorp.com/license-faq)

I am interested in using this change in my project - what needs to happen to promote it?

2024-08-08 17:20 UTC, nileshgadgi commented on versions.tf
> +  required_version = ">= 1.5.7"
1.5.7 or above version will also support BSL, so I guess no need to downgrade the terraform version.
https://www.hashicorp.com/license-faq#products-covered-by-bsl
@rhhammond @Moep90

2024-08-08 17:20 UTC, nileshgadgi requested changes
upgrade the terraform version back to 1.6.6.

2024-08-12 13:09 UTC, anmolnagpal approved these changes

2024-08-29 16:44 UTC, nileshgadgi approved these changes
LGTM!

2024-08-29 16:44 UTC, nileshgadgi commented on versions.tf
> +  required_version = ">= 1.5.7"
we sholud 1.5.7 version to enable support BSL

2024-09-04 11:49 UTC, merged